# The game or mod root load directory (same as "-game" in Source launch parms).
# SourceMod files should be structured as:
# <soup.py root dir>
# |
# └───<game_dir>
#     |
#     └───"addons"
#         |
#         └───"sourcemod"
game_dir: NeotokyoSource

# Encoding to be used for the source code files handled by the updater.
encoding: utf-8

# 0: silent except errors
# 1: some basic informational output
# 2: more output for debugging purposes
verbosity: 1

# List of URLs to JSON files from which to query for updates.
# Please see the relevant documentation for required JSON file syntax.
recipes:
    - https://cdn.jsdelivr.net/gh/CreamySoup/recipe-neotokyo@main/neotokyo_common.json

# GitHub Personal Access Token. Fill one in if your IP address gets rate-limited;
# it will bump your requests-per-hour limit from 60 to 5000, and is not IP address bound.
# For security, this should always be a dummy token with zero GitHub access scopes/permissions.
# https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
gh_username: ""
gh_personal_access_token: ""
